CREATE TABLE AllUserDbs (ID INT IDENTITY(1,1),DBName VARCHAR(MAX))
INSERT INTO AllUserDbs SELECT [NAME] FROM sys.databases WHERE database_id>4
DECLARE @J INT
DECLARE @I INT
DECLARE @DBNAME VARCHAR(MAX)
SET @I=1
SELECT @J=COUNT(*) FROM AllUserDbs
WHILE @I<=@J
BEGIN
SELECT @DBNAME=DBName FROM AllUserDbs WHERE ID=@I
EXEC ('DROP DATABASE ' + @DBNAME)
SET @I=@I+1

END